[2022-10-17 15:26:04,770: INFO/MainProcess] Task sign_in[ae85082c-f88a-4c5a-abf3-5d147bf417a3] received
[2022-10-17 15:26:04,827: WARNING/ForkPoolWorker-1] a@a.com
[2022-10-17 15:26:04,827: WARNING/ForkPoolWorker-1] onboard_user_sign_in
[2022-10-17 15:26:04,827: WARNING/ForkPoolWorker-1] ...
[2022-10-17 15:26:04,833: INFO/ForkPoolWorker-1] Task sign_in[ae85082c-f88a-4c5a-abf3-5d147bf417a3] succeeded in 0.062223357999755535s: None
[2022-10-17 15:26:53,748: INFO/MainProcess] Task sign_in[341aef80-bb7c-467d-8506-7311fad7cf3c] received
[2022-10-17 15:26:53,755: WARNING/ForkPoolWorker-1] a@a.com
[2022-10-17 15:26:53,755: WARNING/ForkPoolWorker-1] onboard_user_sign_in
[2022-10-17 15:26:53,755: WARNING/ForkPoolWorker-1] ...
[2022-10-17 15:26:53,759: INFO/ForkPoolWorker-1] Task sign_in[341aef80-bb7c-467d-8506-7311fad7cf3c] succeeded in 0.009513785000308417s: None
[2022-10-17 15:27:30,453: INFO/MainProcess] Task sign_up[696f0270-b588-4a35-908c-12af023f5e43] received
[2022-10-17 15:27:30,458: WARNING/ForkPoolWorker-1] user@example.com
[2022-10-17 15:27:30,458: WARNING/ForkPoolWorker-1] send welcome email
[2022-10-17 15:27:30,458: WARNING/ForkPoolWorker-1] sent
[2022-10-17 15:27:30,458: WARNING/ForkPoolWorker-1] ...
[2022-10-17 15:27:40,477: INFO/ForkPoolWorker-1] Task sign_up[696f0270-b588-4a35-908c-12af023f5e43] succeeded in 10.023324589998083s: ('user@example.com', 'OK')
[2022-10-17 15:28:21,996: INFO/MainProcess] Task sign_in[cbf61702-83b8-43f5-82b5-0792605e7760] received
[2022-10-17 15:28:22,002: WARNING/ForkPoolWorker-1] a@a.com
[2022-10-17 15:28:22,002: WARNING/ForkPoolWorker-1] onboard_user_sign_in
[2022-10-17 15:28:22,002: WARNING/ForkPoolWorker-1] ...
[2022-10-17 15:28:22,006: INFO/ForkPoolWorker-1] Task sign_in[cbf61702-83b8-43f5-82b5-0792605e7760] succeeded in 0.008496100002957974s: None
[2022-10-17 15:28:34,480: INFO/MainProcess] Task sign_in[fe4f1409-dc2e-4920-b485-34a1d68e1b0b] received
[2022-10-17 15:28:34,486: WARNING/ForkPoolWorker-1] a@a.com
[2022-10-17 15:28:34,486: WARNING/ForkPoolWorker-1] onboard_user_sign_in
[2022-10-17 15:28:34,486: WARNING/ForkPoolWorker-1] ...
[2022-10-17 15:28:34,490: INFO/ForkPoolWorker-1] Task sign_in[fe4f1409-dc2e-4920-b485-34a1d68e1b0b] succeeded in 0.009340171996882418s: None
[2022-10-17 15:28:40,225: WARNING/MainProcess] Exception ignored in atexit callback
[2022-10-17 15:28:40,226: WARNING/MainProcess] : 
[2022-10-17 15:28:40,226: WARNING/MainProcess] <function _exit_function at 0x7f2ee2d1fe20>
[2022-10-17 15:28:40,226: WARNING/MainProcess] Traceback (most recent call last):
[2022-10-17 15:28:40,226: WARNING/MainProcess]   File "/usr/lib/python3.10/multiprocessing/util.py", line 334, in _exit_function
[2022-10-17 15:28:40,226: WARNING/MainProcess]     
[2022-10-17 15:28:40,227: WARNING/MainProcess] _run_finalizers(0)
[2022-10-17 15:28:40,227: WARNING/MainProcess]   File "/usr/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
[2022-10-17 15:28:40,227: WARNING/MainProcess]     
[2022-10-17 15:28:40,227: WARNING/MainProcess] finalizer()
[2022-10-17 15:28:40,227: WARNING/MainProcess]   File "/usr/lib/python3.10/multiprocessing/util.py", line 224, in __call__
[2022-10-17 15:28:40,227: WARNING/MainProcess]     
[2022-10-17 15:28:40,228: WARNING/MainProcess] res = self._callback(*self._args, **self._kwargs)
[2022-10-17 15:28:40,228: WARNING/MainProcess]   File "/external/test_proj/venv/lib/python3.10/site-packages/billiard/pool.py", line 1662, in _terminate_pool
[2022-10-17 15:28:40,228: WARNING/MainProcess]     
[2022-10-17 15:28:40,229: WARNING/MainProcess] cls._help_stuff_finish(*help_stuff_finish_args)
[2022-10-17 15:28:40,229: WARNING/MainProcess]   File "/external/test_proj/venv/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 1341, in _help_stuff_finish
[2022-10-17 15:28:40,229: WARNING/MainProcess]     
[2022-10-17 15:28:40,229: WARNING/MainProcess] readable, _, again = _select(inqR, timeout=0.5)
[2022-10-17 15:28:40,230: WARNING/MainProcess]   File "/external/test_proj/venv/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 165, in _select
[2022-10-17 15:28:40,230: WARNING/MainProcess]     
[2022-10-17 15:28:40,230: WARNING/MainProcess] return poll(readers, writers, err, timeout)
[2022-10-17 15:28:40,230: WARNING/MainProcess]   File "/external/test_proj/venv/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 121, in _select_imp
[2022-10-17 15:28:40,230: WARNING/MainProcess]     
[2022-10-17 15:28:40,230: WARNING/MainProcess] events = poller.poll(timeout)
[2022-10-17 15:28:40,231: WARNING/MainProcess]   File "/external/test_proj/venv/lib/python3.10/site-packages/celery/apps/worker.py", line 299, in _handle_request
[2022-10-17 15:28:40,231: WARNING/MainProcess]     
[2022-10-17 15:28:40,231: WARNING/MainProcess] raise exc(exitcode)
[2022-10-17 15:28:40,231: WARNING/MainProcess] celery.exceptions
[2022-10-17 15:28:40,231: WARNING/MainProcess] .
[2022-10-17 15:28:40,231: WARNING/MainProcess] WorkerTerminate
[2022-10-17 15:28:40,231: WARNING/MainProcess] : 
[2022-10-17 15:28:40,232: WARNING/MainProcess] 1
[2022-10-17 15:28:41,877: INFO/MainProcess] Connected to redis://localhost:6379//
[2022-10-17 15:28:41,882: INFO/MainProcess] mingle: searching for neighbors
[2022-10-17 15:28:42,891: INFO/MainProcess] mingle: all alone
[2022-10-17 15:28:42,901: INFO/MainProcess] celery@ashkan ready.
[2022-10-17 15:28:51,973: INFO/MainProcess] Task sign_in[3554f58a-2b35-463c-b5d4-97d2bc852c30] received
[2022-10-17 15:28:52,035: WARNING/ForkPoolWorker-1] a@a.com
[2022-10-17 15:28:52,035: WARNING/ForkPoolWorker-1] onboard_user_sign_in
[2022-10-17 15:28:52,035: WARNING/ForkPoolWorker-1] ...
[2022-10-17 15:28:52,038: INFO/ForkPoolWorker-1] Task sign_in[3554f58a-2b35-463c-b5d4-97d2bc852c30] succeeded in 0.06414985499941395s: ('a@a.com', 'OK')
